base_params = {
    "vocab_size_char": 1700,
    "vocab_size_word": 8000,
    "embed_size_word": 200,
    "embed_size_char": 200,
    "filters": 300,
    "kernel_size": 3,
    "strides": 1,
    "padding": "same",
    "conv_activation": "relu",
    "embedding_matrix": [],
    "w_initializer": "random_uniform",
    "b_initializer": "zeros",
    "dropout_rate": 0.2,
    "mlp_activation": "relu",
    "mlp_layers_num": 1,
    "mlp_units_num": 128,
    "mlp_fan_out_num": 128,
    "input_shapes": [(64,), (64,)],
    "task": "classification",
}